name: vastu_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  shared_preferences: ^2.5.4
  go_router: ^17.0.1
  dio: ^5.9.0
  razorpay_flutter: ^1.4.0
  # Video Player - YouTube
  youtube_player_flutter: ^9.0.1
  # For video caching
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.7
  flutter_cached_pdfview: ^0.4.3
  permission_handler: ^12.0.1
  firebase_messaging: ^16.1.0
  firebase_core: ^4.3.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android: true
  android_12:
    image: assets/images/android-12-icon.png
    color: "#FFFFFF"
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/images/
